In [1]:
import numpy as np
import pandas as pd

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
df = pd.read_csv("Sentiment Analysis Dataset.csv",encoding='latin1')
df.head(10)

,ItemID,Sentiment,SentimentText
0,1,0,is so sad for my APL frie...
1,2,0,I missed the New Moon trail...
2,3,1,omg its already 7:30 :O
3,4,0,.. Omgaga. Im sooo im gunna CRy. I'...
4,5,0,i think mi bf is cheating on me!!! ...
5,6,0,or i just worry too much?
6,7,1,Juuuuuuuuuuuuuuuuussssst Chillin!!
7,8,0,Sunny Again Work Tomorrow :-| ...
8,9,1,handed in my uniform today . i miss you ...
9,10,1,hmmmm.... i wonder how she my number @-)


In [3]:
sentence = df['SentimentText']
labels = df['Sentiment']

In [4]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentence)
sequences = tokenizer.texts_to_sequences(sentence)
print(sequences[:5])

[[9, 17, 121, 11, 7, 115238, 265], [1, 248, 3, 88, 899, 1483], [318, 73, 195, 474, 480, 311], [189324, 60, 485, 60, 1528, 565, 148, 95, 23, 30, 1506, 297, 761, 1, 25, 22032, 81, 20, 31, 4, 6793, 343, 14, 10022], [1, 74, 1847, 1497, 9, 5029, 14, 13, 437, 437]]


In [61]:
X = pad_sequences(sequences, maxlen=5)

print(X)

[[   121     11      7 115238    265]
 [   248      3     88    899   1483]
 [    73    195    474    480    311]
 ...
 [   652   1163    130     17   1908]
 [     0      0    383      7    217]
 [     0      0    383      7    217]]


In [62]:
y = np.array(labels)
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [76]:
model = Sequential([
    Embedding(input_dim=50000, output_dim=8, input_length=5),

    SimpleRNN(16),

    Dense(1, activation='sigmoid')
])

In [77]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [86]:
model.fit(
    X,
    y,
    epochs=50,
    verbose=1,
    batch_size = 32768
)

Epoch 1/50
32/32 [==============================] - 1s 17ms/step - loss: 0.4052 - accuracy: 0.8046
Epoch 2/50
32/32 [==============================] - 0s 14ms/step - loss: 0.4047 - accuracy: 0.8047
Epoch 3/50
32/32 [==============================] - 0s 15ms/step - loss: 0.4045 - accuracy: 0.8048
Epoch 4/50
32/32 [==============================] - 0s 14ms/step - loss: 0.4043 - accuracy: 0.8050
Epoch 5/50
32/32 [==============================] - 0s 14ms/step - loss: 0.4039 - accuracy: 0.8053
Epoch 6/50
32/32 [==============================] - 0s 14ms/step - loss: 0.4037 - accuracy: 0.8054
Epoch 7/50
32/32 [==============================] - 0s 14ms/step - loss: 0.4035 - accuracy: 0.8054
Epoch 8/50
32/32 [==============================] - 0s 13ms/step - loss: 0.4034 - accuracy: 0.8056
Epoch 9/50
32/32 [==============================] - 0s 14ms/step - loss: 0.4031 - accuracy: 0.8056
Epoch 10/50
32/32 [==============================] - 0s 14ms/step - loss: 0.4030 - accuracy: 0.8057
Epoch 11/

In [83]:
test = ["I love this film"]

seq = tokenizer.texts_to_sequences(test)

pad = pad_sequences(seq, maxlen=5)

prediction = model.predict(pad)

print(prediction)

1/1 [==============================] - 0s 103ms/step
[[0.9202497]]


In [84]:
# Evaluate the model
loss, accuracy = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

KeyboardInterrupt: 